### ISSUE TITLE
If DaemonSet contrail-agent need toleration ?

### ISSUE THREAD

**Issue by heisenbergye** [Juniper/contrail-kubernetes-docs#17]
Learning from contrail-standalone-kubernetes architecture, there is no need to deploy contrail-agent  on the master node，so I delete the spec.template.spec.tolerations in DaemonSet contrail-agent. Because the vhost0 has a network failure after contrail-agent initialized on the master node，although there is a default route via vhost0 in host's route-table. 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: contrail-agent
  namespace: kube-system
  labels:
    app: contrail-agent
spec:
  template:
    metadata:
      labels:
        app: contrail-agent
    spec:
      #tolerations:
      #- key: node-role.kubernetes.io/master
        #operator: Exists
        #effect: NoSchedule
      automountServiceAccountToken: false
      hostNetwork: true
      initContainers:
      - name: contrail-node-init
        image: "docker.io/opencontrailnightly/contrail-node-init:latest"
        imagePullPolicy: ""
        securityContext:
          privileged: true
```
